<?php
// $Id$

/**
 * @file
 * Server functions for chat invitations.
 *
 * Explanation.
 */

/**
 * @defgroup invite Sending invitations
 * @{
 * Description.
 *
 * Explanation.
 */

/**
 * Set up filters.
 */

/**
 * Give users permission to invite others.
 */

/**
 * Give users permission to moderate others' chats.
 */

/**
 * Give users permission to own others' chats.
 */

/**
 * Add user status to database.
 */

/**
 * Retrieve user status from database.
 */

/**
 * Add invitation to database.
 */

/**
 * @} End of "defgroup invite"
 */

/**
 * @defgroup join Accepting invitations
 * @{
 * Description.
 *
 * Explanation.
 */

/**
 * Set up filters
 */

/**
 * Retrieve invitations matching filter from database.
 */

/**
 * @} End of "defgroup join"
 */
