<?php
// $Id$

/**
 * @file
 * Node chat server functions.
 *
 * Explanation.
 */

/**
 * @ingroup message
 * @{
 */

/**
 * Add comment to database.
 */

/**
 * Delete comment from database.
 */

/**
 * Update comment in database.
 *   Replace content.
 *   Update modification timestamp (need to add a modification time column to
 *   the comments table).
 */

/**
 * Retrieve comment from database.
 */

/**
 * @} End of "ingroup message"
 */

/**
 * Interface
 *   Node content
 *   Comments
 *     Add
 *     Edit
 *     Delete
 *     Vote
 *   Status of users
 *     Invite
 *   Control access
 *     View
 *     Comment
 *     Moderate
 */
